name: Atualizar JSON

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes to JSON
        run: |
          # Seus comandos para atualizar o JSON

      - name: Commit and push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Seu Nome"
          git add .
          git commit -m "Atualizando JSON automaticamente"
          git push origin main
